/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package user;

import javax.swing.JOptionPane;
import business.Login;
import data.EmployeeDB;
import data.LoginDB;
import java.awt.Desktop;
import java.io.File;
import java.io.IOException;
/**
 *
 * @author kariy
 */
public class MainUI extends javax.swing.JFrame {

    /**
     * Creates new form MainUI
     */
    public MainUI() {
        initComponents();
        setLocationRelativeTo(this);
        if (LoginStatus.login.equals("Admin")) {
            mnuNewEmployeeLogin.setEnabled(true);
        }
        if (LoginStatus.login.equals("HR_Manager")) {
            mnuEmployee.setEnabled(true);
        }
        
    }
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        mnuFile = new javax.swing.JMenu();
        mnuEmployee = new javax.swing.JMenuItem();
        mnuClose = new javax.swing.JMenuItem();
        mnuLogin = new javax.swing.JMenu();
        mnuNewEmployeeLogin = new javax.swing.JMenuItem();
        mnuLogout = new javax.swing.JMenuItem();
        mnuHelp = new javax.swing.JMenu();
        mnuGuide = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMenuBar1.setBackground(new java.awt.Color(255, 255, 255));

        mnuFile.setText("File");

        mnuEmployee.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.CTRL_MASK));
        mnuEmployee.setText("Employee");
        mnuEmployee.setEnabled(false);
        mnuEmployee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuEmployeeActionPerformed(evt);
            }
        });
        mnuFile.add(mnuEmployee);

        mnuClose.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_MASK));
        mnuClose.setText("Close");
        mnuClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuCloseActionPerformed(evt);
            }
        });
        mnuFile.add(mnuClose);

        jMenuBar1.add(mnuFile);

        mnuLogin.setText("Login");

        mnuNewEmployeeLogin.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_MASK));
        mnuNewEmployeeLogin.setText("New Employee Login");
        mnuNewEmployeeLogin.setEnabled(false);
        mnuNewEmployeeLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuNewEmployeeLoginActionPerformed(evt);
            }
        });
        mnuLogin.add(mnuNewEmployeeLogin);

        mnuLogout.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.CTRL_MASK));
        mnuLogout.setText("Logout");
        mnuLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuLogoutActionPerformed(evt);
            }
        });
        mnuLogin.add(mnuLogout);

        jMenuBar1.add(mnuLogin);

        mnuHelp.setText("Help");

        mnuGuide.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_H, java.awt.event.InputEvent.CTRL_MASK));
        mnuGuide.setText("Guide");
        mnuGuide.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuGuideActionPerformed(evt);
            }
        });
        mnuHelp.add(mnuGuide);

        jMenuBar1.add(mnuHelp);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 244, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 156, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnuEmployeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuEmployeeActionPerformed
        // TODO add your handling code here:
        EmployeeUI empUI = new EmployeeUI();
        empUI.setVisible(true);
    }//GEN-LAST:event_mnuEmployeeActionPerformed

    private void mnuCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuCloseActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_mnuCloseActionPerformed

    private void mnuNewEmployeeLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuNewEmployeeLoginActionPerformed
        // TODO add your handling code here:
        NewEmployeeLoginUI newEmp = new NewEmployeeLoginUI();
        newEmp.setVisible(true);
    }//GEN-LAST:event_mnuNewEmployeeLoginActionPerformed

    private void mnuLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuLogoutActionPerformed
        // TODO add your handling code here:
        LoginUI logUI=new LoginUI();
        logUI.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_mnuLogoutActionPerformed

    private void mnuGuideActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuGuideActionPerformed
        // TODO add your handling code here:
        try {
        // Replace "path_to_your_file" with the actual path to your file
        String filePath = "path_to_your_file";
        // Open the file using the default file opener of the system
        Desktop.getDesktop().open(new File("D:/HD67/Guide.docx"));
    } catch (IOException ex) {
        // Handle any potential exceptions here
        ex.printStackTrace();
        JOptionPane.showMessageDialog(this, "Error opening file: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_mnuGuideActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem mnuClose;
    private javax.swing.JMenuItem mnuEmployee;
    private javax.swing.JMenu mnuFile;
    private javax.swing.JMenuItem mnuGuide;
    private javax.swing.JMenu mnuHelp;
    private javax.swing.JMenu mnuLogin;
    private javax.swing.JMenuItem mnuLogout;
    private javax.swing.JMenuItem mnuNewEmployeeLogin;
    // End of variables declaration//GEN-END:variables
}
